### ISSUE TITLE
I think I developed an Idea but IDK where to publish it.

### ISSUE THREAD

**Issue by alchemistake** [sebastianotronto/fmctutorial#1]
I have a method I'm working on for a while I think it is human impossible to do in a competition but I would like to publish it before someone else gets the same idea :D So where Can I publish it and get it seen in FMC community. I've been dabbling in FMC for 3-5 years or so but never got involved the community directly.

It is actually directly inspired from your FMC WR solve. So IDK whether it is known or not.

Idea is called "Nullators" and born from the fact that "U' D B2 D B2 U D' R2 D' R2" does not change cube state. And We can use it to reduce move count with it. I called it "Null Reduction" and wrote a python script to generate all the possible (under certain length.)

**Comment by sebastianotronto** [comment]
Hi! You can post it on the speedsolving.com forum in the [FMC thread](https://www.speedsolving.com/threads/the-fmc-thread.13599/), or make a new thread if you like. Don't forget to add one or more example solves if you have them, they are very useful when presenting new methods :-)

Many cubers stopped using the forum and started using Facebook instead, so it's a good idea to advertise in the [Fewest Moves](https://www.facebook.com/groups/1422080808012720) Facebook group (if you can't access the group you can make a request and someone will approve it).

**Comment by alchemistake** [comment]
Ah I hate facebook. I miss good old days of forums!!! Thanks for the help I'll try to compile and send something to facebook.
